package com.business.erp.auth.enums;

public enum LoginAuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    USER_CREATED,
    PASSWORD_CHANGE,
    FORGOT_PASSWORD_REQUESTED,
    PASSWORD_RESET,
    TEMPORARY_PASSWORD_RESET,
    ACCOUNT_ENABLED,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    EMPLOYEE_LINKED,
    EMPLOYEE_UNLINKED,
    EMPLOYEE_ACCESS_REVOKED
}
