package com.business.erp.settings.enums;

public enum SettingKey {
    PAID_LEAVES_PER_MONTH,
    STANDARD_WORKING_HOURS,
    STANDARD_WORKING_DAYS,
    OVERTIME_MULTIPLIER,
    LOAN_DEFAULT_INTEREST_RATE,
    SALARY_PAYMENT_DAY,
    LOW_STOCK_ALERT_ENABLED,
    MONTH_CLOSING_REQUIRES_PAYROLL
}
