package com.business.erp.settings.enums;

public enum SettingKey {
    PAID_LEAVES_PER_MONTH,
    STANDARD_WORKING_HOURS,
    STANDARD_WORKING_DAYS,
    OVERTIME_MULTIPLIER,
    LOAN_DEFAULT_INTEREST_RATE,
    SALARY_PAYMENT_DAY,
    LOW_STOCK_ALERT_ENABLED,
    MONTH_CLOSING_REQUIRES_PAYROLL,
    WEEKLY_OFF_DAYS,WEEKLY_OFF_MULTIPLIER,
    HOLIDAY_OT_MULTIPLIER,
    LEAVE_ALLOCATION_METHOD,
    UNUSED_PAID_LEAVE_POLICY,
    LEAVE_CARRY_FORWARD_LIMIT,
    PAYROLL_GENERATION_POLICY,
    LEAVE_ENCASHMENT_ENABLED
}